export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USER_LOCATION = 'SET_USER_LOCATION';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_UPDATE_QUANTITY = 'CART_UPDATE_QUANTITY';
export const CART_SET_CHEF = 'CART_SET_CHEF';
export const CART_CLEAR = 'CART_CLEAR';
export const CART_SEND_NOTIFICATION = 'CART_SEND_NOTIFICATION';
export const CART_RESET_NOTIFICATION = 'CART_RESET_NOTIFICATION';
